#!/bin/bash

# TeamCity Integration Script
# This script prepares your flaky test demo for TeamCity

echo "🚀 TeamCity Integration Setup"
echo "=============================="
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}Step 1: Prepare Your Repository${NC}"
echo "================================="
echo ""
echo "Option A: Use GitHub (Recommended)"
echo "1. Create a new GitHub repository"
echo "2. Push the flaky-test-demo code:"
echo ""
echo "   cd /Users/satish/qlp-projects/TeamCity/flaky-test-demo"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit: Flaky test demo'"
echo "   git remote add origin https://github.com/YOUR_USERNAME/flaky-test-demo.git"
echo "   git push -u origin main"
echo ""
echo "Option B: Use TeamCity's built-in Git"
echo "1. In TeamCity, use 'Manual Setup'"
echo "2. Upload the project as a ZIP file"
echo ""

echo -e "${BLUE}Step 2: Configure TeamCity Project${NC}"
echo "===================================="
echo ""
echo "In TeamCity (as shown in your screenshot):"
echo ""
echo "1. Click '+ Create project' or 'New Project'"
echo "2. Select 'From a repository URL' and enter your GitHub URL"
echo "   OR select 'Manually' and upload the project"
echo ""
echo "3. Project Settings:"
echo "   - Name: 'Flaky Test Demo'"
echo "   - Project ID: 'FlakyTestDemo'"
echo "   - Description: 'Demonstrates intelligent flaky test detection'"
echo ""

echo -e "${BLUE}Step 3: Configure Build Configuration${NC}"
echo "======================================="
echo ""
echo "TeamCity should auto-detect Node.js. If not, manually configure:"
echo ""
echo "Build Steps:"
echo "1. Command Line or Node.js step:"
echo "   - Script: npm install"
echo ""
echo "2. Command Line or Node.js step:"
echo "   - Script: npm run test:junit"
echo ""
echo "3. Build Features → Add Build Feature:"
echo "   - XML Report Processing"
echo "   - Report type: JUnit"
echo "   - Monitoring rules: '+:test-results/*.xml'"
echo ""

echo -e "${BLUE}Step 4: Enable Test Intelligence${NC}"
echo "=================================="
echo ""
echo "1. Go to Build Configuration Settings"
echo "2. Build Features → Add Build Feature"
echo "3. Select 'Test History' (if available)"
echo "4. Enable 'Automatic Test Failure Investigation'"
echo ""
echo "Note: Some features are enabled by default in TeamCity Cloud"
echo ""

echo -e "${BLUE}Step 5: Run Multiple Builds${NC}"
echo "============================="
echo ""
echo "To see flaky test detection in action:"
echo ""
echo "1. Run the build at least 5 times"
echo "2. After 3-5 builds, you'll see:"
echo "   - Tests marked as 'Ignored' (flaky)"
echo "   - Failure rates displayed"
echo "   - Build stays 'Success' despite flaky failures"
echo ""

echo -e "${GREEN}Ready to demonstrate TeamCity's intelligence!${NC}"
echo ""
echo "Your tests will show patterns like in your screenshot:"
echo "• InternalCommandDocumentationTest - multiple failures"
echo "• SystemInfopageDocSourceTest - intermittent failures"
echo "• IntegrationTest - flaky behavior"
echo ""
echo "TeamCity will automatically categorize them!"
